controllers: 
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_start:
    path: /start
    controller: App\Controller\StartController::index
    methods: [GET]

saludo_usuario:
    path: /saludo/{nombre}
    controller: App\Controller\StartController::saludoUsuario
    methods: [GET]

app_bienvenida:
    path: /bienvenida
    controller: App\Controller\StartController::bienvenida
    methods: [GET]